### ISSUE TITLE
Задание

### ISSUE THREAD

**Issue by lpsztemp** [130120013/AVIGenerator#1]
Интерфейс
```cpp
template <class Caller>
void generateAVI(const char* file_name, Caller&& get_value, unsigned width, unsigned height, unsigned frames, double val_min, double val_max, bool discard_file);
```
Сгенерировать видеофайл, несжатый AVI, с именем file_name, в TrueColor, длительностью frames / 25 секунд.

file_name - имя выходного файла;
get_value - пользовательский функтор, который возвращает некоторое значение типа double для тройки значений типа unsigned, где первое значение - индекс стлобца, второе - индекс строки, а третье - номер текущего кадра в видео,
width - ширина в пикселах,
height - высота в пикселах,
frames - количество кадров,
val_min - минимальное значение, которое может быть возвращено функтором get_value,
val_max - ммаксимальное значение, которое может быть возвращено функтором get_value,
discard_file - флаг замены содержимого файла file_name, если такой файл уже существует. Если файл существует, а флаг сброшен, функция должна завершаться с ошибкой.

**Comment by 130120013** [comment]
Генерация AVI работает, ведется тестирование
